Update 0005-repair-tf-card.patch

diff --git a/patches/0005-repair-tf-card.patch b/patches/0005-repair-tf-card.patch
--- a/patches/0005-repair-tf-card.patch
+++ b/patches/0005-repair-tf-card.patch
@@ -5,7 +5,7 @@ Subject: [PATCH] repair tf card
 
 ---
  .../armv8/base-files/etc/init.d/repair_ro     |  7 +++
- .../rockchip/armv8/base-files/sbin/repair_ro  | 52 +++++++++++++++++++
+ .../rockchip/armv8/base-files/sbin/repair_ro  | 60 +++++++++++++++++++
  .../armv8/base-files/usr/bin/repair_ro        |  3 ++
  3 files changed, 61 insertions(+)
  create mode 100755 target/linux/rockchip/armv8/base-files/etc/init.d/repair_ro
@@ -20,7 +20,7 @@ index 0000000000..8d8a5bde49
 @@ -0,0 +1,7 @@
 +#!/bin/sh /etc/rc.common
 +
-+START=99
++START=22
 +
 +start() {
 +    /sbin/repair_ro
@@ -30,59 +30,67 @@ new file mode 100755
 index 0000000000..094f0f0a70
 --- /dev/null
 +++ b/target/linux/rockchip/armv8/base-files/sbin/repair_ro
-@@ -0,0 +1,52 @@
+@@ -0,0 +1,60 @@
 +#!/bin/sh
-+# Created by Frizkyiman
-+# Github https://github.com/frizkyiman/
 +
-+_echo() {
++log_message() {
 +  [ "$1" = 'err' ] && echo $2 >&2 || echo $2
 +  logger -p "$1" -t repair_co "$2"
 +}
 +
-+if [ -n "$1" ]; then
-+    root_device="$1"
-+    if ! blkid | grep -q "$root_device:"; then
-+        _echo err "Root file system device '$root_device' not found in the system. Unable to repair."
-+        exit 1
-+    fi
-+else
-+    root_device=$(blkid -L rootfs -o device)
-+fi
++RC_LOCAL="/etc/rc.local"
++ROOT_DEVICE=$(blkid -L rootfs -o device)
++REPAIR_LOCK="/root/repairlock"
 +
-+if [ -z "$root_device" ]; then
-+    _echo err "Root file system device not found in the system. Unable to repair."
++
++reboot_system(){
++  touch "$REPAIR_LOCK"
++  log_message "notice" "Rebooting the system..."
++  reboot
++  
++  if [ $? -ne 0 ]; then
++    log_message "err" "Reboot command failed. Please try a forced reboot using reboot -f"
++  fi
++}
++
++main(){
++  if [ -z "$ROOT_DEVICE" ]; then
++    log_message "err" "Root file system device not found. Unable to repair."
 +    exit 1
-+fi
-+
-+ro_status=$(mount | awk '$root_device && /ro,/ {print $6}' | grep -o 'ro' | head -n 1)
-+
-+if [ "$ro_status" = "ro" ]; then
-+    _echo notice "Detected root file system: $root_device"
-+    _echo notice "The file system is currently read-only. Initiating repair..."
-+
-+    if e2fsck -y "$root_device"; then
-+        _echo notice "File system repair successful."
-+        _echo notice "Mounting $root_device to read-write"
-+        mount -o remount,rw "$root_device" /
-+        _echo notice "Rebooting the system..."
-+        rm -rf /etc/rc.d/S99repair_ro
-+        reboot
-+        if [ $? -ne 0 ]; then
-+            _echo err "Reboot command failed. Please try force reboot if necessary using reboot -f"
-+        fi
++  fi
++  
++  RO_STATUS=$(mount | grep -w "$ROOT_DEVICE" | grep -o 'ro' | head -n 1)
++  
++  if [ "$RO_STATUS" = "ro" ]; then
++    log_message "notice" "Root file system '$ROOT_DEVICE' is read-only. Initiating repair..."
++    
++    if e2fsck -y "$ROOT_DEVICE"; then
++      log_message "notice" "File system repair successful."
++      log_message "notice" "Remounting '$ROOT_DEVICE' as read-write."
++      mount -o remount,rw "$ROOT_DEVICE" /
++      
++      if [ -e "$REPAIR_LOCK" ]; then
++        rm -f /etc/rc.d/S22repair_ro
++        sed -i '/#repair tf#/,/#repair tf#/d' "$RC_LOCAL"
++        sed -i "/^exit 0/i #repair tf#\ne2fsck -y $ROOT_DEVICE\nmount -o remount,rw /\n#repair tf#" "$RC_LOCAL"
++        rm -f "$REPAIR_LOCK"
++      else
++        reboot_system
++      fi
 +    else
-+        _echo notice "An error occurred while repairing the file system."
-+        _echo notice "Trying to reboot if possible"
-+        _echo notice "please try force reboot if nothing happen using reboot -f"
-+        reboot
-+        if [ $? -ne 0 ]; then
-+            _echo err "Reboot command failed. Please try force reboot if necessary using reboot -f"
-+        fi
++      log_message "err" "An error occurred during file system repair."
++      
++      if [ ! -e "$REPAIR_LOCK" ]; then
++        log_message "notice" "Attempting to reboot..."
++        reboot_system
++      fi
 +    fi
-+else
-+    _echo notice "Root file system device '$root_device' is currently in read-write mode."
-+fi
++  else
++    log_message "notice" "Root file system '$ROOT_DEVICE' is already in read-write mode."
++  fi
++}
++
++main
 diff --git a/target/linux/rockchip/armv8/base-files/usr/bin/repair_ro b/target/linux/rockchip/armv8/base-files/usr/bin/repair_ro
 new file mode 100755
 index 0000000000..cee9b226e6
@@ -94,4 +102,3 @@ index 0000000000..cee9b226e6
 +/sbin/repair_ro "$root_device"
 -- 
 2.25.1
-
