Added upload to TG

diff --git a/.github/workflows/openwrt-builder-Latest.yml b/.github/workflows/openwrt-builder-Latest.yml
--- a/.github/workflows/openwrt-builder-Latest.yml
+++ b/.github/workflows/openwrt-builder-Latest.yml
@@ -10,12 +10,14 @@
 # See /LICENSE for more information.
 #
 
-name: OpenWrt Builder  Latest
+name: OpenWrt Builder Latest
 
 on:
   repository_dispatch:
   workflow_dispatch:
-
+  schedule:
+    - cron: '0 4 1 * *'
+    
 env:
   REPO_URL: https://github.com/coolsnowwolf/lede
   REPO_BRANCH: master
@@ -23,11 +25,12 @@ env:
   CONFIG_FILE: .config
   DIY_P1_SH: scripts/diy-part1.sh
   DIY_P2_SH: scripts/diy-part2.sh
+  UPLOAD_TO_TG_SH: scripts/upload-to-telegram.sh
   ENV_SH: scripts/environment.sh
   FREE_DISK_SH: scripts/free_disk_space.sh
   PATCHES_DIR: patches6.1
   UPLOAD_BIN_DIR: true
-  UPLOAD_FIRMWARE: true
+  UPLOAD_FIRMWARE: false
   UPLOAD_RELEASE: true
   TZ: Asia/Shanghai
 
@@ -169,7 +172,26 @@ jobs:
         tag_name: ${{ steps.tag.outputs.release_tag }}
         body_path: release.txt
         files: ${{ env.FIRMWARE }}/*
-
+        
+    - name: Upload firmware to telegram
+      env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      if: steps.tag.outputs.status == 'success' && !cancelled()
+      run: |
+        if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
+            echo "TELEGRAM_BOT_TOKEN is missing!"
+            exit 0
+        fi
+        chmod +x UPLOAD_TO_TG_SH
+        cd $FIRMWARE
+ 
+        CAPTION="kernel $KERNEL_PATCHVER for lede source code
+            [仓库](https://github.com/${{ github.repository }}/)
+            [下载地址: ${{ steps.tag.outputs.release_tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.tag.outputs.release_tag }})" 
+        FILE_NAME=openwrt-rockchip-armv8-xunlong_orangepi-r1-plus-lts-ext4-sysupgrade.img.gz
+        
+        UPLOAD_TO_TG_SH -file $FILE_NAME -token ${{ secrets.TELEGRAM_BOT_TOKEN  }} -chatid ${{ secrets.TELEGRAM_CHAT_ID  }} -caption "$CAPTION" -prefix r1-plus-lts-$KERNEL_PATCHVER || true
+    
     - name: Delete workflow runs
       uses: Mattraks/delete-workflow-runs@main
       with:
